### ISSUE TITLE
Shorten time of running the code 

### ISSUE THREAD

**Issue by mauimoana** [dczifra/epidemic_seeding#2]
Hi, Doctor dczifra：

The paper about epidemic seeding you guys published does interest me a lot. However, the code upload seems not working. The error I come about is attached below.  Could you give me some suggestions? Thanks a lot.

<FileNotFoundError: [Errno 2] No such file or directory: '/home/hewenchao/anaconda_2/anaconda_2/lib/python3.8/site-packages/infectionmodelling-1.0-py3.8.egg/src/bin/main'>

Best wishes.

**Comment by dczifra** [comment]
Which file do you run? Could you build the source code?

**Comment by wenchaohee** [comment]
I am trying to re-implement the code in <epidemic_seeding/paper/results_GIRG-Config.ipynb>. The error arose from these codes.
![image](https://user-images.githubusercontent.com/77086328/143361885-d3461226-d866-4d52-881a-691c48f282f1.png)
The codes above these lines work well.
 I  only installed the <-e . >file.  I didn't build the c++ and GPU files.
Thanks for your time and reply.

Best wishes.

**Comment by dczifra** [comment]
As you can see in the README.md, you need to build the c++ code, because the .ipynb you are using needs it.
Go to the home folder of your repository, and build the source code with the command:
`./src/bin/build_cpp` (You will need bash, and g++)

**Comment by wenchaohee** [comment]
Thanks very much for your advice. Having tried many times, I still come about a  problem and  I don't know what to do to fix this.
![8224}1L6{XB O VB(JQB4N2](https://user-images.githubusercontent.com/77086328/143415735-f28089fa-cd09-45a4-a56e-8a5b0d2ff0c0.png)
Could give me some suggestions? 

Best wishes.

**Comment by dczifra** [comment]
You have to make it runnable first:
`chmod +x ./src/bin/build_cpp`

**Comment by wenchaohee** [comment]
Great thanks for your kind help. The problem mentioned has been solved. Running the codes.

Best wishes.

**Comment by wenchaohee** [comment]
Hi, Dr. Czifra:

Thanks to your kind advice, the problem mentioned above was solved. However, two days have past since the beginning of running the code, I was wondering how long does it generally takes to finish the code. Are there any parameters that could be compromised to shorten the time but get similar results of the original code? 

Thanks for your time. Best wishes.

**Comment by wenchaohee** [comment]
I can‘t read the files. 〒_〒
![image](https://user-images.githubusercontent.com/77086328/143981650-6e64cb97-3341-41ea-b981-0f38845c5b1e.png)

**Comment by dczifra** [comment]
You can speed up the computations, if you have a lot of cores; by increasing args["procnum"] to the number of cores you have.
The phenomenon is computed:
1.  on 2x4x25 differently seeded  random graph (2 for GIRG/Config model, 4 for different (alpha,tau) parameters, 25 for random seed). You can decrease the random seed easily, but you can decrease the the computed models too.
2. each data point (for given graph and beta) is computed args["simnum"] times, you can decrease that parameter too.
3. you can have more rough beta linspace

**Comment by dczifra** [comment]
Sorry, the log folders are not consistent. Move the /your_repo_folder/paper/data/girgs_final into /your_repo_folder/paper/girgs_final.

**Comment by mauimoana** [comment]
Hi, Dr. Czifra:

Thank you for your detailed and helpful advice. I roughly get similar results of your ipython code. However, the problem that I mentioned above-- there is an error in reading the file, in fact, is okay. On the contrary, It seems that there is a bug in saving the file.
![image](https://user-images.githubusercontent.com/77086328/144188334-aabcaae1-0fb8-4420-9701-896cbe1a4650.png)

I fixed this problem with a dumb method. I simply save the file on the current director. I am not sure whether it is the problem of my implementation or the original code. Anyway, I had gotten the general results of your ipython code.

Thanks very much for your effort and time. Best wishes.

**Comment by dczifra** [comment]
Thanks for your review, I updated the notebook, it is logging to the folder, where it is needed for the plots.

**Comment by mauimoana** [comment]
It's absolutely my pleasure. Wish you Merry Christmas in advance! （＾ｖ＾）

**Comment by mauimoana** [comment]
Hi, Dr. Czifra:
Sorry to bother you again. Though the code now runs well, I'm a little confused with the meaning of some parameters of
 your codes, especially the meaning of _random_seed_num_  and  _inf_city_.  I think that it will be a nicer work if you could add more annotations of the codes. 
![360截图20211227171645277](https://user-images.githubusercontent.com/77086328/147457351-43e85a80-3477-45f5-bde6-088d2adeecb4.jpg)

Best wishes
